### ISSUE TITLE
完善作业详情的显示

### ISSUE THREAD

**Issue by ErisPluto** [NewTeam5/EduCnblogs#147]
1.调整页面适应屏幕大小
2.已截止的作业不显示“提交作业”按钮，或点击后提醒不能提交作业
3.不显示未开始的作业

**Comment by ZiJiaW** [comment]
解决了长网址换行问题，现在不能提交截止的作业，作业列表不显示未开始作业，4h

**Comment by ErisPluto** [comment]
👍
