### ISSUE TITLE
作业部分API包装

### ISSUE THREAD

**Issue by ErisPluto** [NewTeam5/EduCnblogs#15]
完成作业部分API的包装：
主要包括获取当前班级作业、根据id获取作业、获取作业提交列表、获取未提交作业成员、提交作业
<b>写好注释：包括方法用途、传入参数类型及含义、返回数据类型和含义</b>

**Comment by Issac-Newton** [comment]
在最开始提交的代码中添加了作业部分获取的内容，但是作业部分涉及操作的部分因为还没有进行过测试，所以还没有添加
