### ISSUE TITLE
作业部分交互

### ISSUE THREAD

**Issue by ErisPluto** [NewTeam5/EduCnblogs#16]
1.完成作业列表和作业详情及提交页面的切换：点击作业标题跳转到作业详情页面、点击提交作业按钮显示弹出框。
2.完成数据的显示：包括作业列表（每条包括标题、摘要、相关信息：发布者、发布日期、提交人数）、作业详情（标题、相关信息、状态、详细内容、已提交成员表格、未提交成员）
3.完成与API的对接：包括获取显示数据、提交作业、提交作业后页面的刷新

**Comment by ZiJiaW** [comment]
还未完成，先添加了作业列表页面和作业详情页面，实现传入classID通过API获取作业列表，以及两个页面之间的跳转，UI部分交给奕君美化吧（CSS不行），用时8h（很多坑）。
