### ISSUE TITLE
对班级列表、个人博客部分进行测试

### ISSUE THREAD

**Issue by ErisPluto** [NewTeam5/EduCnblogs#35]
1.测试登录后提交评论和回复的功能
2.测试用户在自己的博客和在他人博客中不同的权限
3.测试获取用户所在班级的功能
4.测试用户的不同身份在班级中的不同权限

**Comment by wz111** [comment]
1、评论回复功能基本实现，但是评论数目更新很慢
2、好像自己的博客和别人的博客权限没什么区别，不涉及修改博文内容啥的，评论可以评论别人，也可以评论自己
3、获取功能实现
4、老师可以添加学生，学生不能添加成员
用时：6h
对某些组件添加了accessibilitylabel属性，测试代码放在__test__/testcode下
