### ISSUE TITLE
UI设计准备工作

### ISSUE THREAD

**Issue by ErisPluto** [NewTeam5/EduCnblogs#4]
<ul><li>熟悉React Native 组件</li><li>熟悉JavaScript中的面向对象编程、函数、快速入门<.li><li>寻找备用UI素材库</li></ul>

**Comment by yaoling1997** [comment]
了解了react native基本组件
了解了JavaScript中的面向对象编程、函数、快速入门
备用UI素材库网址:http://ibaotu.com/shejiyuansu/?chan=bd&label=poster&plan=C2-bd&kwd=4717
3h
