### ISSUE TITLE
测试发布、创建功能

### ISSUE THREAD

**Issue by ErisPluto** [NewTeam5/EduCnblogs#46]
1.对新增的发表、删除评论、回复进行测试
2.对创建班级功能进行测试
3.对作业发布功能进行测试

**Comment by wz111** [comment]
1、在addCommentTest.py中已经测过。
2、暂未实现创建班级功能。
3、作业添加不成功，内容格式无法修改，截止时间无法选择，标题和内容好像无法显示。
测试代码是postHomeworkTest.py，在testcode中
用时：1h
