### ISSUE TITLE
熟悉博客园API

### ISSUE THREAD

**Issue by ErisPluto** [NewTeam5/EduCnblogs#6]
用postman对项目中需要使用的API进行测试

**Comment by Issac-Newton** [comment]
能够测试的已经完成测试。
因为有些api会修改博客园中的内容，没有进行测试。
测试的api大部分能够使用，2、3个不能用
实际用时：2.5小时

**Comment by ErisPluto** [comment]
关于投票的api可以暂时不管，其他的可以明天联系博客园工作人员找到正确的使用方法。测试的主要目的是方便后面写关于api的代码。如果难以解决，可以及时反馈。如果顺利解决，反馈最终时间花费。
